### PR TITLE
Expansion of CONTRIBUTING

### PR DESCRIPTION
**Pull request by Psifour**
Still requires documentation for Translation/Localization efforts and a PR template.

### CODE REVIEW

**Comment by raphjaph** [comment]
I'll convert to Draft since it's not ready for review yet

**Comment by Psifour** [comment]
Absolutely should be a draft, I have no knowledge of any translation/localization being worked on currently and would love an assist if you know who is doing so (assuming it is being done).

I have a PR template (based on GitHub template) that I typically use, can be seen on #1669. If this is acceptable as a starting point I will include it in documentation for now.

**Comment by Psifour** [comment]
Localization and PR templates were put in backlog. Documentation ready, but a proof-read or grammatical review would be appreciated.

**Review by casey — CHANGES_REQUESTED** [review]
Sorry for letting this sit! This is great stuff, but the `CONTRIBUTING` file really functions as a legal disclaimer which informs contributors of the copyright status of their contributions, should they make them. I'd like to keep it short. Also, check out the [contributing docs page](https://docs.ordinals.com/contributing.html), it might overlap with this. I think the right move here is to merge these changes into the contributing docs page.

**Pull request closed without merging**
