### PR TITLE
Identifying inscriptions

### PR DESCRIPTION
**Pull request by raphjaph**
At the moment `ord` only parses new inscriptions that are in the first input of a transaction. This PR rectifies this mistake by also parsing inscriptions on other transaction inputs. This will make future improvements like batch inscriptions and parent-child relationships easier. Out of this follows that there can now be `inscription_id`s that end with `...i1`,`...i54`/, etc. (not only `...i0`). The number at the end is just the index of the inscription in the transaction. Another question is which sat an inscription is inscribed on. At the moment it is the first sat of the first output but this is implicit. If there is multiple inscription inputs but only one output, which sat is the second inscription inscribed on? Does there have to be a seperate output for the inscription to be valid or is it just discarded if a corresponding output is missing? Through an optional (uneven) tag we could build pointers to the sat the inscription is supposed to be on. It could specify the sat offset in the transaction as the sat this inscription is inscribed on. Here with offset=1000:
```
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_3
  OP_PUSH 1000
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "first inscription"
OP_ENDIF
```

Thinking even further a more general consensus question arises as well. Should it be possible to have more than one inscription *per input*? Practically, this would be achieved by putting multiple of our envelope constructions in the input's witness, like so:
```
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "first inscription"
OP_ENDIF
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "second inscription"
OP_ENDIF
```
Having multiple inscriptions per input would make batch inscriptions way more space efficient since an inscription wouldn't need an extra input.

#2000 
#1769

### CODE REVIEW

**Comment by veryordinally** [comment]
This PR addresses #2000 

I would suggest to move the broader protocol questions regarding multiple inscriptions per transaction and multiple inscriptions per input to separate issues to facilitate discussion and review.

**Comment by casey** [comment]
This is not ready for a PR, because we haven't decided how to proceed. Changing it to a draft to reflect this.

**Comment by casey** [comment]
I'm on mobile, and I couldn't figure out how to make this PR a draft, so I closed it instead.

**Comment by raphjaph** [comment]
How do we decide how to proceed?

**Comment by casey** [comment]
This is a big change, and we've started tackling smaller pieces independently, so this can be closed.

**Pull request closed without merging**
