### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by sbddesign**
Fixed typo "use maintain"

### CODE REVIEW

**Review by Psifour — CHANGES_REQUESTED** [review]
Grammar still feels awkward. Maybe something more in-line with "Transaction Index support must be enabled in Bitcoin Core by adding the following to your `bitcoin.conf`"

**Comment by sbddesign** [comment]
I disagree. Your proposal puts the sentence into passive voice, which appears to contradict the way the other sentences are written (at a cursory glance).

**Comment by Psifour** [comment]
That is an acceptable opinion. 
I can fully agree that the "use" was grammatically incorrect.

**Comment by casey** [comment]
Discussion and an ack on a typo fix, making my life as a maintainer so easy❤️

Tried to merge, but phone UI is terrible, will merge later.

In general, anything that is a pareto improvement can be insta-merged, and feedback/improvements can be deferred to a follow-up issue. A typo or grammar fix is almost always a Pareto improvement.

Open PRs are my highest priority queue items, so I always want to merge, convert to draft, or close, to keep things moving.

**Pull request merged**
