### PR TITLE
Remove default for parameter `--fee-rate` for `wallet send`

### PR DESCRIPTION
**Pull request by veryordinally**
Implement issue #1747 
Given high fee environment many users run into issue with default fee rate of 1. 

Review checklist:
- [x] Does it have tests?
- [x] Does this work for wallet send and wallet inscribe? Any other places where we pick a fee rate? (Fixed by noting in #1747 that we need to also do this for wallet inscribe.)
- [x] Have the docs been updated?

### CODE REVIEW

**Comment by RarePepeMaximalist** [comment]
This looks good to me -- I think we should also make `--fee-rate` a required parameter on `ord inscribe` ?

Also we should update the guide to use `--fee-rate` in the example
https://github.com/casey/ord/blob/master/docs/src/guides/inscriptions.md

**Comment by veryordinally** [comment]
Updated the guide, thanks @RarePepeMaximalist for the pointer.

Update for `ord inscribe` makes sense to me for consistency.

**Comment by droplister** [comment]
Please include in your review this piece of code. If you are sending an amount of sats rather than an inscription, it will use an RPC command that does not take a --fee-rate at all, but relies on the default behavior of `send_to_address`.

I think this means that even if you require a fee rate, it will not be utilized in this instance.

https://github.com/casey/ord/blob/b0ca48658d1b5eb911e1a2e3afea675134f9ba4d/src/subcommand/wallet/send.rs#L51-L74

**Comment by casey** [comment]
Great point @droplister! This is actually the root problem behind #1432. So extremely nice find!

**Pull request merged**
