### PR TITLE
Upgrade to redb 0.11.0

### PR DESCRIPTION
**Pull request by cberner**
I haven't finished benchmarking the mmap backend against the new safe one, so I left ord using the mmap backend.

### CODE REVIEW

**Comment by casey** [comment]
Nice! Thanks for the PR! Can `AccessGuard<T>` implement `Deref<T>`? Not sure if this is possible, but if it were, it might make them slightly more convenient.

**Comment by cberner** [comment]
I don't think that's possible today, because `.value()` returns the lifetime of `&self`. If they have a `LendingDeref` in the future that would work though.

**Comment by casey** [comment]
Can't `Deref::deref` borrow `&self`? 

The trait is `fn deref(&self) -> &Self::Target;` which has an elided lifetime, so it's actually `fn deref<'a>(&'a self) -> &'a Self::Target;`

**Comment by cberner** [comment]
oh right, duh. I mixed this up with a different issue I had =P The problem with `Deref` is that it returns `&Self::Target`, but I need to return `Self::Target` for types like `u64`

**Pull request merged**
