### PR TITLE
[Typo] Fix singular of "genesis" on transaction page

### PR DESCRIPTION
**Pull request by tudormunteanu**
Minor fix: unsure if plural was the intention or a minor typo, but I see no indication of multiple inscriptions.

### CODE REVIEW

**Comment by nammaki** [comment]
Merge this already 😓

**Comment by tudormunteanu** [comment]
> Merge this already 😓

Easy there. I think they have bigger fish to fry. This PR can wait.

**Comment by nammaki** [comment]
> > Merge this already 😓
> 
> Easy there. I think they have bigger fish to fry. This PR can wait.

I didn't intend to offend so I'm sorry if it came off rough, it's just sad to see so many positive contributions neglected ❤️

**Comment by raphjaph** [comment]
You are correct, in practice there is only one new inscription per transaction (inscription genesis) but in theory can be multiple inscriptions per transaction. We haven't implemented this yet, but here is a PR that does: #2006. So closing this since the plural (geneses) is the generally correct term.

**Pull request closed without merging**
